// All built-in Ableton Live devices that can be inserted via the SDK
export const BUILTIN_DEVICES: string[] = [
  // Audio Effects
  "Amp",
  "Auto Filter",
  "Auto Pan",
  "Beat Repeat",
  "Cabinet",
  "Channel EQ",
  "Chorus-Ensemble",
  "Compressor",
  "Corpus",
  "Dynamic Tube",
  "Echo",
  "EQ Eight",
  "EQ Three",
  "Erosion",
  "Filter Delay",
  "Flanger",
  "Frequency Shifter",
  "Gate",
  "Glue Compressor",
  "Grain Delay",
  "Limiter",
  "Looper",
  "Multiband Dynamics",
  "Overdrive",
  "Pedal",
  "Phaser-Flanger",
  "Redux",
  "Resonators",
  "Reverb",
  "Roar",
  "Saturator",
  "Shifter",
  "Spectral Blur",
  "Spectral Resonator",
  "Spectrum",
  "Tuner",
  "Utility",
  "Vinyl Distortion",
  "Vocoder",
  // MIDI Effects
  "Arpeggiator",
  "Chord",
  "Macro Variations",
  "MIDI Monitor",
  "Note Echo",
  "Note Length",
  "Pitch",
  "Random",
  "Scale",
  "Velocity",
  // Racks
  "Audio Effect Rack",
  "Instrument Rack",
  "MIDI Effect Rack",
  // Instruments
  "Analog",
  "Collision",
  "Drift",
  "Drum Rack",
  "Electric",
  "Impulse",
  "Meld",
  "Operator",
  "Sampler",
  "Simpler",
  "Tension",
  "Wavetable",
];
